# Generated by Django 6.0.3 on 2026-04-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_notification_raw_data',
        ),
    ]
