# Generated by Django 6.0.3 on 2026-04-09 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_communication', '0002_delete_order_notification_raw_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('message_id', models.CharField(max_length=100)),
                ('notification_recieved_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('notification_recieved_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
