# Generated by Django 6.0.3 on 2026-04-09 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_data_observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('message_id', models.CharField(max_length=100)),
                ('notification_recieved_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipping_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order_data_observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('shipping_id', models.CharField(max_length=100)),
                ('notification_recieved_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='message_data',
        ),
        migrations.DeleteModel(
            name='order_data',
        ),
    ]
