# Generated by Django 6.0.3 on 2026-04-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0004_message_data_observation_order_data_observation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registered_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('processed', 'processed')], max_length=20)),
                ('notification_id', models.CharField(max_length=100)),
            ],
        ),
    ]
