# Generated by Django 6.0.3 on 2026-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0005_registered_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ml_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
