# Generated by Django 6.0.3 on 2026-04-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0006_ml_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_order',
            name='notification_id',
        ),
        migrations.RemoveField(
            model_name='registered_order',
            name='status',
        ),
        migrations.AddField(
            model_name='registered_order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registered_order',
            name='last_notification_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registered_order',
            name='seller_message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registered_order',
            name='order_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
