# Generated by Django 6.0.3 on 2026-04-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0007_remove_registered_order_notification_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_status_code', models.IntegerField()),
                ('api_response_text', models.TextField()),
                ('api_response_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='message_data_observation',
        ),
        migrations.DeleteModel(
            name='order_data_observation',
        ),
    ]
