# Generated by Django 6.0.3 on 2026-04-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0008_api_error_delete_message_data_observation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_credentials',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ml_credentials',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
