# Generated by Django 6.0.3 on 2026-04-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0009_alter_ml_credentials_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_order',
            name='last_notification_at',
        ),
        migrations.RemoveField(
            model_name='registered_order',
            name='seller_message_sent',
        ),
        migrations.AlterField(
            model_name='api_error',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registered_order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
