# Generated by Django 6.0.3 on 2026-04-21 16:58
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0010_remove_registered_order_last_notification_at_and_more'),
    ]

    operations = []
