# Generated by Django 6.0.3 on 2026-04-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0011_alter_ml_credentials_access_token'),
    ]

    operations = []
