# Generated by Django 6.0.3 on 2026-04-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0012_alter_ml_credentials_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_credentials',
            name='access_token',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ml_credentials',
            name='refresh_token',
            field=models.CharField(max_length=100),
        ),
    ]
