# Generated by Django 6.0.3 on 2026-04-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0014_alter_ml_credentials_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_credentials',
            name='access_token',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ml_credentials',
            name='refresh_token',
            field=models.CharField(max_length=100),
        ),
    ]
