# Generated by Django 6.0.3 on 2026-04-23 18:06

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0015_alter_ml_credentials_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_credentials',
            name='access_token',
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='ml_credentials',
            name='refresh_token',
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
    ]
