# Generated by Django 6.0.3 on 2026-04-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0016_alter_ml_credentials_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ml_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('delivery_arrangement', 'delivery_arrangement'), ('customer_inquiries', 'customer_inquiries')], max_length=30)),
                ('message_text', models.CharField(max_length=350)),
            ],
        ),
    ]
