# Generated by Django 6.0.3 on 2026-04-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_communication', '0017_ml_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_messages',
            name='message_text',
            field=models.TextField(max_length=350),
        ),
    ]
